services:
        web:
                build: ./docker/web
                ports:
                        - "5000"
        db:
                build: ./docker/db_server
                ports:
                        - "3000"
        nginx:
                image: nginx:latest
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf:ro
                depends_on:
                        - web
                ports:
                        - "5000:5000"
