// The redirector module implements a web server that redirects requests
// according to the hashes generated by the web module.
package main

import (
	"log"
	"net/http"
	"os"
)

func main() {

	port := os.Getenv("PORT")

	if port == "" {
		port = "5001"
		log.Printf("$PORT not set, defaulting to %v", port)
	}

	http.HandleFunc("/", redirectHandler)

	http.ListenAndServe(":"+port, nil)
}
